services:
  auth-service:
    build:
      context: ./auth_service
      target: dev
    ports:
      - "8002:8000"
    environment:
      - KEYCLOAK_SERVER_URL=https://keycloack.dfcubidesc.com
      - KEYCLOAK_CLIENT_ID=auth-service
      - KEYCLOAK_REALM_NAME=habit-tracker
      - KEYCLOAK_CLIENT_SECRET_KEY=DF4sNVjM7YqB31S7gYyGhhcvDxBNeC2j
      - REDIS_HOST=redis-cache
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=secret
      - OTEL_SERVICE_NAME=auth-service
      - OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=http://otel-collector:4318/v1/logs
    depends_on:
      - redis-cache
      - vacation-planner
    networks:
      - default
      - observability
    volumes:
      - ./auth_service:/app

  vacation-planner:
    build:
      context: ./vacation_stay_scrapper
      target: primary
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://vacation:vacation@postgres:5432/vacation_planner
      - OTEL_SERVICE_NAME=vacation-planner
      - OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=http://otel-collector:4318/v1/logs
    depends_on:
      - postgres
    networks:
      - default
      - observability
    volumes:
      - ./vacation_stay_scrapper:/vacation_stay_scrapper

  flight-service:
    build:
      context: ./flight_service
      target: primary
    environment:
      - SERVER=${SERVER:-rest}
    ports:
      - "8001:8080"
    volumes:
      - ./flight_service:/flight_service

  recommendations:
    build:
      context: ./recommendations

  fe-client:
    build:
      context: ./fe-client
      target: dev
    ports:
      - "3001:3001"
    volumes:
      - ./fe-client/src:/app/src
      - ./fe-client/index.html:/app/index.html
      - ./fe-client/vite.config.js:/app/vite.config.js

networks:
  observability:
    external: true
    name: vacationplanner-codingdojo_observability
