version: "3.9"
services:
  vacation-planner:
    build:
      context: ./vacation_stay_scrapper
      target: primary
    ports:
      - "8000:8000"
    volumes:
      - ./vacation_stay_scrapper:/app
  flight-scrapper:
    build: ./flight_scrapper_service
    ports:
      - "8001:8080"
    volumes:
      - ./flight_scrapper_service:/app

  vacation-planner-tests:
    build:
      context: ./vacation_stay_scrapper
      target: tests

  flight-scrapper-tests:
    build:
      context: ./flight_scrapper_service
      target: tests