version: "3.9"
services:
  vacation-planner:
    build: ./vacation_stay_scrapper
    ports:
      - "8000:8000"
    volumes:
      - ./vacation_stay_scrapper:/app
  flight-scrapper:
    build: ./flight_scrapper_service
    ports:
      - "8001:5000"
    volumes:
      - ./flight_scrapper_service:/app