services:
  redis-cache:
    image: redis
    environment:
      - REDIS_PASSWORD=secret
      - REDIS_USER=secret
    ports:
      - "6379:6379"
  redis-ui:
    image: redis/redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis-cache

  vacation-planner:
    build:
      context: ./vacation_stay_scrapper
      target: primary
    ports:
      - "8000:8000"
    volumes:
      - ./vacation_stay_scrapper:/vacation_stay_scrapper
  flight-scrapper:
    build:
      context: ./flight_scrapper_service
      target: primary
    environment:
      - SERVER=${SERVER:-rest}
    ports:
      - "8001:8080"
    volumes:
      - ./flight_scrapper_service:/flight_scrapper_service

  vacation-planner-tests:
    build:
      context: ./vacation_stay_scrapper
      target: tests
    volumes:
      - ./vacation_stay_scrapper:/vacation_stay_scrapper

  flight-scrapper-tests:
    build:
      context: ./flight_scrapper_service
      target: tests
    volumes:
      - ./flight_scrapper_service:/flight_scrapper_service

  selenium-hub:
    image: selenium/hub:latest
    platform: linux/amd64
    environment:
      - log-level=FINE
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  node-1:
    image: selenium/node-firefox:latest
    ports:
      - "5555:5555"
    environment:
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - log-level=FINE

  node-2:
    image: selenium/node-chrome:latest
    platform: linux/amd64
    ports:
      - "5556:5555"
    depends_on:
      - selenium-hub
    environment:
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - log-level=FINE
    shm_size: 2g
  
  broker:
    image: apache/kafka:latest
    container_name: broker
    environment:
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://broker:9092,CONTROLLER://broker:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092  # in case of need an external access change this for the external URL
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_MIN_INSYNC_REPLICAS: 1
    ports:
      - "9092:9092"
      - "9093:9093"
