version: "3.9"
services:
  redis-cache:
    image: redis
    environment:
      - REDIS_PASSWORD=secret
      - REDIS_USER=secret
    ports:
      - "6379:6379"
  redis-ui:
    image: redis/redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis-cache

  vacation-planner:
    build:
      context: ./vacation_stay_scrapper
      target: primary
    ports:
      - "8000:8000"
    volumes:
      - ./vacation_stay_scrapper:/app
  flight-scrapper:
    build:
      context: ./flight_scrapper_service
      target: primary
    environment:
      - SERVER=rest
    ports:
      - "8001:8080"
    volumes:
      - ./flight_scrapper_service:/app

  vacation-planner-tests:
    build:
      context: ./vacation_stay_scrapper
      target: tests

  flight-scrapper-tests:
    build:
      context: ./flight_scrapper_service
      target: tests

  selenium-hub:
    image: selenium/hub:latest
    environment:
      - log-level=FINE
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  node-1:
    image: selenium/node-chrome:latest
    ports:
      - "5555:5555"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - log-level=FINE

  node-2:
    image: selenium/node-chrome:latest
    ports:
      - "5556:5555"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443