flights:
  main_url: http://flights:8000/
  available_routes:
    - /search_flight
    - /get_flights
    - /

vacation-planner:
  main_url: http://vacation-planner:8000/
  available_routes:
    - /api/trips
    - /api/trips/*
    - /api/trips/*/flights/*/status
    - /api/trips/*/accommodations/*/status
    - /api/trips/*/activities/*/status