services:
  vacation-planner-tests:
    build:
      context: ../vacation_stay_scrapper
      target: tests
    volumes:
      - ../vacation_stay_scrapper:/vacation_stay_scrapper

  flight-scrapper-tests:
    build:
      context: ../flight_service
      target: tests
    volumes:
      - ../flight_service:/flight_service
