POST http://localhost:8080/get_flights

{
    "airline": "avianca",
    "search_params": {
        "origin": "origin",
        "destination": "destination",
        "arrival_date": "2023-10-10",
        "return_date": "2023-10-20"
    }
}
###
### GET request to example server
GET localhost:8080/



###