name: Deploy to Amazon ECS
run-name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: vacationplanner
  ECS_SERVICE: vacation_stay_scrapper
  ECS_CLUSTER: vacation-planner
  ECS_TASK_DEFINITION: vacation-planner
  CONTAINER_NAME: vacation_stay_planner
  DIRECTORY: vacation_stay_scrapper,flight-scrapper-service




permissions:
  contents: read


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{fromJson(env.DIRECTORY)}}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker image from ${{ matrix.directory }}
      run: |
        docker build -t test-image-${{ matrix.directory }} ./${{ matrix.directory }}

  deploy:
    needs: [test]
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        max-parallel: [ 2 ]
        folders: ${{ fromJson(needs.micro-services.outputs.dockerfile_folders) }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        DOCKER_HUB_USERNAME : ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_REPOSITORY : "fs-service"
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo ${{ matrix.folders }} 
        cd ${{ matrix.folders }}
        docker build -t $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:${{ matrix.folders }}_$IMAGE_TAG .
        docker push $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:$IMAGE_TAG
        echo "image=$DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
